format = """
$directory\
$git_branch\
$line_break\
$character """

[directory]
format = "[$read_only]($read_only_style)[$path]($style) "
style = "fg:#89b4fa"
truncation_length = 3  # Show last 3 folders
truncate_to_repo = true  # Show path relative to git repo root
home_symbol = "~"

[git_branch]
format = "[$branch]($style) "
style = "fg:#f5c2e7"

[character]
success_symbol = "[🚀](bold)"
error_symbol = "[💥](bold)"

[git_status]
disabled = true

[package]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[golang]
disabled = true

[java]
disabled = true

[cmd_duration]
disabled = true
